spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.205.183.240:3306/easy_find?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: root
    password: 666111
mybatis-plus:
  configuration:
    #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    map-underscore-to-camel-case: false
    #关闭自动转换小驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl